-- Table pour les étapes de prise en charge
CREATE TABLE etape_prise_en_charge (
    id_etape BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prise_en_charge_id BIGINT NOT NULL REFERENCES prise_en_charge(id_prise_en_charge) ON DELETE CASCADE,
    ordre INT NOT NULL,
    type VARCHAR(50), -- ex: Diagnostic, Traitement, Surveillance, Chirurgie
    description TEXT NOT NULL,
    date_debut TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    date_fin TIMESTAMP WITH TIME ZONE,
    etat VARCHAR(20) DEFAULT 'A faire', -- A faire, En cours, Terminé, Annulé
    observation TEXT,
    acteur VARCHAR(50), -- ex: Infirmier, Médecin, Aide-soignant
    est_approuve BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Index pour accélérer la recherche par prise en charge
CREATE INDEX idx_etape_pec_id ON etape_prise_en_charge(prise_en_charge_id);
