spring.application.name=hospital-management-pfa

# Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.rogfplheaoaibrumrgla
spring.datasource.password=pswd@dyal!supabase
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=hospital_management_super_secret_key_2024_pfa_projet_fin_annee_secure_256bits
jwt.expiration=86400000

# Désactive UserDetailsService auto
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
logging.level.org.springframework.security=DEBUG
logging.level.com.hospital=DEBUG
# Server
server.port=8080